### ISSUE TITLE
Warnings come up for loan terms that are well within boundaries (W0182)

### ISSUE THREAD

**Issue by MattMcB** [cfpb/regtech-data-validator#146]
With values like '715' we get warnings like "when present, 'loan term' should be less than 1200(100 years)."

**Comment by hkeeler** [comment]
@MattMcB, just to confirm, this is the bug you mentioned when we met last time?

**Comment by MattMcB** [comment]
> @MattMcB, just to confirm, this is the bug you mentioned when we met last time?
yis

**Comment by hkeeler** [comment]
Great. We'll check it out. Thanks!

**Comment by jcadam14** [comment]
Then problem is the is_less_than function doesn't convert the strings to ints.  So we're doing a straight string compare with  
```
    check_result = value < max_value
    return _check_blank_(value, check_result, accept_blank)
```
